CycloneDX/transparency-exchange-api

- README.md
- api/bomexchangeapi.md
- doc/tea-requirements.md
- doc/tea-usecases.md
- update readme based on the new work
- add information about ECMA
- move the existing API to separate document
> Update documentation from our Google doc "use cases" documentation

- doc/tea-requirements.md
Was unclear there was a difference sentence start here
> Add period

- tea-index/README.md
A first draft documenting some of the decisions made in the meeting June 19th, 2024 - including some open issues.
> tea-index: Adding a rough draft based on discussions in Koala wg meeting

- discovery/readme.md
Add missing `https` in discovery worked example.
> fix: typo in Discovery readme.md

- tea-collection/tea-collection.md
Adding an outline for discussion in our meeting.
> tea collection: Adding a first description

- doc/tea-usecases.md
Based on discussions in #24 we have to expand the use cases with different stuff that people want to apply TEA on, deliverables that needs a TEI for discovery.
> TEA use cases: Adding a new category for the work on the object model

- discovery/readme.md
Add a few TEI types that works in the TEI library at
https://github.com/SBOMEurope/tei-parser-lib
> Discovery: Add details on TEI types

- tea-collection/tea-collection.md
And some ideas about ENUM reason for update
> Collection: Adding author info

- tea-leaf/tea-leaf.md
Based on discussions in meeting Sept 11
> TEA LEAF Object: A model for discussion

- api-flow/consumer.md
Adding a first mermaid diagram
> Adding an overview of API

- api-flow/publisher.md
> Adding publishing sequence diagram proposal from Chris Langton 

- tea-collection/tea-collection.md
* Adapt wording to ensure more dynamic artifacts such as LCE and VEX are mentioned
* Fix Table rendering of Update Types
Related to issue #57
> Adapt TEA Collection Object documentation

- discovery/readme.md
This PR primarily drafts changes to resolve #64.
Additional clarifications have been made in relation to other work under discussion:
- #30 
- #66 
- #67
> Updated Discovery to cater for move to SVCB DNS records

- discovery/readme.md
Update to consistently refer to the final portion of the TEI as `unique-identifier`.
> Updated discovery/readme

- .gitignore
- api-flow/consumer.md
- api-flow/publisher.md
- spec/README.md
- spec/openapi.json
* Completes OpenAPI specs with missing building blocks
* Synchronizes workflow diagram with API specs
* Minor documentation fixes
> Tweak OpenAPI specs and workflows

- doc/tea-requirements.md
> Requirements: Add security txt, fix some issues

- .github/workflows/test-generate-api-clients.yaml
- spec/openapi.yaml
Resolves #116.
FYI @ppkarwasz @oej @vpetersson
> fix: Corrected various OpenAPI Spec errors to get valid Spec document

- README.md
- api-flow/consumer.md
- api-flow/publisher.md
- tea-component/tea-component.md
- tea-index/tea-index.md
Going through markdown files to rename TEA LEAF to TEA COMPONENT.
> Renaming TEA LEAF to TEA COMPONENT

- api-flow/consumer.md
Add more details on components
> Update the API flow

- api-flow/consumer.md
Update with the new release object
> Update API-flow mermaid diagrams

- tea-collection/tea-collection.md
> Updating the Collection, adding the new Release object

- contributors.md
Adding a list of contributors. 
* If you are missing, let me know
* Please add affiliation, email, and GitHub account if you want that to be part of the doc
> Adding contributors

- spec/openapi.yaml
For future compatibility with GraphQL.
> fix: use upper-case enums

- contributors.md
Fixes my entry to contributor.
> Fixes spelling

- discovery/readme.md
> doc: include `CNAME` records in DNS discovery
