- README.md
- discovery/readme.md
Adding a separate document on the current proposal for DNS-based discovery of the API endpoints.
(Mostly copied from Google doc use case document)
> Add discovery proposal

- discovery/readme.md
I believe that this was a copy-paste error and is probably supposed to state "purl" instead of "uuid".
> Fix TEI format for PURLs

- .gitignore
- spec/generators/python.yaml
- spec/openapi.json
This PR resolves initial failures of the GitHub Workflow to build and test generated API clients.
Fixes included:
- Ensuring initial output directory exists (`out`)
- Aligning Python generated package name (see `python.yaml`)
- Generated GO was invalid seemingly due to operations have more than one tag in the OpenAPI spec - moved to single tags
> fix: GH workflows failing

- spec/openapi.json
Root cause of https://github.com/madpah/transparency-exchange-api/actions/runs/11933709569/job/33261312468
> fix: `examples` incorrectly nested for `POST /leaf`

- spec/openapi.json
I forgot to add this in the previous PR.
Closes #81.
> Adds the ability to patch `/product/tea_product_identifier`

- discovery/readme.md
> fix: aligned TEI examples to specification

- api/bomexchangeapi.md
- discovery/readme.md
some fenced code blocks did not have proper syntax hi light, due to wrong/missing language declarations.
This PR will fix this, based on https://github.com/github-linguist/linguist/blob/main/lib/linguist/languages.yml
> fix code fence languages

- tea-leaf/tea-leaf.md
> Leaf: Clarify the prerelease-flag

- discovery/readme.md
- Remove the DNS URI records as a few large DNS providers does not support them (and the RFC is informational)
- Clarify TLS certificate requirements (according to RFC 9640)
- Fix some markdown formatting (make markdownlint happy)
> Discovery: Remove load balancing and failover support using DNS

- spec/generators/common.yaml
Noted a discrepancy that was causing generation of test API client libraries to fail.
> fix: Refer to OpenAPI Spec in YAML format

- auth/readme.md
> Adding first draft of authentication/authorization documentation

- auth/readme.md
Two occurrences of the word `leaf` made it back to the documentation through #98, which was merged after #120.
> Complete renaming of TEA LEAF to TEA COMPONENT

- spec/openapi.yaml
This commit switches to
/product/1234-1234-1244-124324
/products
/tea-component/1234-1234-1244-124324/collections
notations as discussed on the call on 2025-04-16.
Basic linting is also included.
> feat: introduce structure between products, TEA components, collections

- spec/openapi.yaml
This PR modifies the schema of the domain objects according to the structure discussed in the Koala Workshop
> Modifies domain objects after workshop

- spec/openapi.yaml
`examples` must be an array, not an object
> fix: Examples syntax

- spec/openapi.yaml
- tea-collection/tea-collection.md
This PR:
- Updates the fields in the `tea-collection.md` file based on the OpenAPI spec of the TEA Collection object.
- Synchronizes the descriptions between OpenAPI and Markdown.
- Adds an example of TEA Collection (real example of `log4j-core`).
> Clarify TEA Collection fields

- spec/openapi.yaml
- tea-collection/tea-collection.md
- Fixes the fields in the TEA Component Release object, based on those listed in the OpenAPI spec.
- Synchronizes the descriptions used in `tea-collection.md` and the OpenAPI spec.
- Adds four examples of releases of the same TEA Component (Apache Tomcat) that differ in packaging, version numbers and presence of the pre-release flag.
> Clarify TEA Component Release fields

- spec/openapi.yaml
- tea-collection/tea-collection.md
This PR tries to uniformize the naming strategy for JSON properties and parameter names. Since CycloneDX mostly uses `camelCase` instead of `snake_case` or `kebab-case`, I settled to convert everything to camel case.
**Note**: The names that are used internally (e.g., JSON schemas and parameter references) were not modified.
> feat: use `camelCase` for property and parameter names

- spec/openapi.yaml
This change replaces the `tei_urn` query parameter with a pair of `idType/idValue` parameters to filter products using all the available identifiers.
The ideal solution in this case would be to use a single parameter with schema `#/components/schemas/identifier` together with [RFC 6570-style serialization](https://swagger.io/specification/#style-examples):
```yaml
identifier-param:
name: identifierParam
description: If present, only the objects with the given identifier will be returned.
in: query
schema:
$ref: "#/components/schemas/identifier"
style: form
explode: true
```
This is currently not a viable option, since limitations of the `openapi-generator` like OpenAPITools/openapi-generator#4808 would cause bugs in the generated clients.
> feat: find products by identifier

- spec/openapi.yaml
- tea-collection/tea-collection.md
This removes the `author` field from the collection.
Fixes #139
> fix: remove `author` for specification

- spec/openapi.yaml
- tea-collection/tea-collection.md
Many of the [CycloneDX external reference](https://cyclonedx.org/docs/1.6/json/#externalReferences_items_type) types, such as `website` are not very interesting from a security perspective. Since it is easier to add new types than to remove them, this PR trims down the current list to some categories that:
- Should be interesting to access on a TEA server.
- Have machine-readable formats (with a few exceptions).
> feat: trim down TEA Artifact types

- contributors.md
- spec/README.md
The documentation referenced the old JSON format rather than the new YAML file.
> Fixes Swagger API documentation in light of move to YAML from JSON

- signatures/signature.md
Trying to gather thoughts on digital signatures in the TEA collections and for TEA artefacts.
Feedback is always welcome!
> Adding a first draft on handling of digital signatures

- discovery/readme.md
- Add a note about avoiding guessing the TEI
- Add a note about "shared EAN codes" - those are not useful for creating unique TEIs for products that share EAN code. Each product needs a unique TEI.
> Update the discovery

- README.md
- spec/openapi.yaml
- tea-product/tea-product.md
This is to be able to reference a specific release of a component in addition to referencing the component itself.
The product now includes a list of "componentref" objects where each object contains one or two items - the first is a reference to the component, which is required, the second is a reference to specific release of that component, which is optional.
> Adding a "componentref" structure in the product definition

- README.md
- spec/openapi.yaml
- tea-collection/tea-collection.md
- tea-component/tea-component.md
- tea-component/tea-release.md
- tea-product/tea-product-release.md
- tea-product/tea-product.md
This PR adds on top of #186  :
1. Concept of Product Release, as discussed on Community Meeting on 2025-08-13 - this implements Product - Product Release and Component - Component Release paradigm, where Product may still be omitted for certain workflows as we also establish global /productReleases endpoint
2. Fixes minor inconsistencies across schema (i.e. unifying casing and uuid reference)
> Add concept of Product Release with its own Collections

- spec/openapi.yaml
This PR introduces following improvements:
1. Names component releases "componentRelease" in API instead of just "release" for more clarity
2. Removes usage of allOf composite structures in pagination, which previously resulted in creation of unclear classes like "TeaInlineObject1" on generators
3. Adds pagination on releases by product
4. Renames operation identifiers getTeaProductReleaseByIdentifier and getTeaProductByIdentifier to queryTeaProductReleases and queryTeaProducts, since identifiers are optional
5. Introduces /componentRelease endpoint which contains component release details together with its latest collection, also adds component name (this is done in part to cut down on round-tripping)
6. Adds product name in product release endpoint
7. Bumps API spec version for Beta 2
> TEA Improvements Post Product-Component model merge - 2025-09
